authuser/urls.py
from django.urls import path
from authuser.views import *
app_name = 'App_Auth'
urlpatterns = [
  path('login',loginview,name="login"),
  path('logout',logoutview,name="logout"),

 
]

inventory/urls.py
from django.urls import path
from inventory.views import *
app_name = 'App_inventory'
urlpatterns = [
  path('',dashboard,name="dashboard"),
  path('users',userlist,name="userslist"),
  path('adduser',adduser,name="adduser"),
  path('deleteuser',deleteuserdata,name="deleteuser"),
  path('edituser/<int:id>',edituserdata,name="edituser"),
]

joelypos/urls.py
from django.contrib import admin
from django.urls import path,include
admin.site.site_title = 'N-tech Solution'
admin.site.site_header = 'N-tech Solution'
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inventory.urls')),
    path('',include('pos.urls')),
    path('auth/',include('authuser.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pos/urls.py
from django.urls import path
from inventory.views import *
urlpatterns = [
  
]

authuser/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    type=models.IntegerField(default=-1)

    def __str__(self):
        return '{}-{}'.format(self.user,self.type)

inventory/models.py
from django.db import models

# Create your models here.

pos/models.py
from django.db import models

# Create your models here.

authuser/views.py
from django.shortcuts import render,redirect
from django.contrib import messages,auth
from django.contrib.auth import logout as auth_logout, login as auth_login, authenticate
from functools import wraps
import requests


def authenticated_user(view_func) :
    def wrapper_func(request, *args, **kwargs):
        if request.user.is_authenticated and request.session.get('user').get('is_authenticated') :
            return view_func(request, *args, **kwargs)
        else :
            return redirect('App_Auth:login')
    return wrapper_func


def admin_required(view_func):
    @wraps(view_func)
    def wrapper(request, *args, **kwargs):
        if not request.user.is_staff:
            return render(request,'authuser/accessdenied.html')
        return view_func(request, *args, **kwargs)
    return wrapper


def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            messages.success(request,"you are now authenticated")
            url=request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                params=dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except Exception:
                return redirect('App_inventory:dashboard')
        else:
            messages.error(request, "invalid credential")
            return redirect('App_Auth:login')
    context={}
    return render(request,'authuser/login.html')

def logoutview(request):
    auth.logout(request)
    messages.success(request, "Successfully Logout")
    return redirect('App_Auth:login')

inventory/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from authuser.views import admin_required
from django.contrib import messages

@login_required(login_url='App_Auth:login')
@admin_required
def dashboard(request):
    return render(request,'inventory/index.html')


#get all user list
@login_required(login_url='App_Auth:login')
@admin_required
def userlist(request):
    # Retrieve all users except the logged-in user
    users = User.objects.exclude(pk=request.user.pk)
    #make dict to pass data to template
    context={
        'user_list':users,
    }
    return render(request,'inventory/users/users.html',context)


#add user page
@login_required(login_url='App_Auth:login')
@admin_required
def adduser(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        status = request.POST.get('status')
        user_type = request.POST.get('user_type')
        
        if password != confirm_password:
            messages.error(request, "Passwords do not match.")
            return redirect('App_inventory:adduser')
        if User.objects.filter(username=username).exists():
            messages.error(request,"username already exist try another one.")
            return redirect('App_inventory:adduser')
        
        user = User.objects.create_user(
            username=username, 
            password=password, 
            email=email,
        )
        user.first_name = first_name
        user.last_name = last_name
        if status==1:
            user.is_active=True
        else:
            user.is_active=False    

        if user_type==1:
            user.is_staff=True
            user.is_superuser=True
        else:
            user.is_staff=False
            user.is_superuser=False
        user.save()
        messages.success(request,"you have successfully added new user")
        return redirect('App_inventory:adduser')
    else:
        return render(request,'inventory/users/addusers.html')

#add user page
@login_required(login_url='App_Auth:login')
@admin_required    
def edituserdata(request,id):
    try:
        user=User.objects.get(id=id)
        if request.method=="POST":
            print("posting")
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            email = request.POST.get('email')
            status = request.POST.get('status')
            user_type = request.POST.get('user_type')

            user.first_name=first_name
            user.last_name=last_name
            user.email=email
            if status==1:
                user.is_active=True
            else:
                user.is_active=False    
            if user_type==1:
                user.is_staff=True
                user.is_superuser=True
            else:
                user.is_staff=False
                user.is_superuser=False
            user.save()
            user=User.objects.get(id=id)
            messages.success("user update successfully")
            return redirect('App_inventory:userslist')   

    except:
        user=None

    context={
        'user':user
    }
    print(user)
    return render(request,'inventory/users/edit.html',context)    



def deleteuserdata(request):
    # try:
    if request.method=="POST":
        id=request.POST["userdeletemodal"]
        user = get_object_or_404(User, id=id)
        user.delete()
        messages.success(request,"user data deleted")
    else:
        messages.error(request,"something went wrong")          
    return redirect('App_inventory:userslist')    
    # except:
    #     messages.error(request,"something went wrong except")
    #     return redirect('App_inventory:userslist')   

pos/views.py
from django.shortcuts import render

# Create your views here.

templates/alert/alert.html
{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert text-white bg-{{ message.tags }}" {% endif %} role="alert">
        <div class="iq-alert-text">{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error: {% endif %} {{ message }}</div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <i class="ri-close-line"></i>
        </button>
    </div>
    {% endfor %}
{% endif %}

templates/alert/pop.html
{% load static%}
{% if messages %}
    {% for message in messages %}
    <script src="{% static 'assets/js/jquery.js'%}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.success("{{message}}");
    </script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    {% endfor %}
{% endif %}

templates/authuser/accessdenied.html
<!DOCTYPE html>
<html>
<head>
<title>Access Denied</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta charset="UTF-8">
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<style>
    body{
        background-color: black;
        color: white;
    }
        
    h1 {
        color: red;
    }
        
    h6{
        color: red;
        text-decoration: underline;
    }       
</style>    
<body>
<div class="w3-display-middle">
<h1 class="w3-jumbo w3-animate-top w3-center"><code>Access Denied</code></h1>
<hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
<h3 class="w3-center w3-animate-right">You dont have permission to view this page.</h3>
<h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
<h6 class="w3-center w3-animate-zoom">error code:403 forbidden</h6>
</div>
</body>
</html>

templates/authuser/login.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>POS Dash | Responsive Bootstrap 4 Admin Dashboard Template</title>
      
      <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" />
      <link rel="stylesheet" href="{% static 'assets/css/backend-plugin.min.css'%}">
      <link rel="stylesheet" href="{% static 'assets/css/backend.css'%}">
      <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css'%}">
      <link rel="stylesheet" href="{% static 'assets/vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css'%}">
      <link rel="stylesheet" href="{% static 'assets/vendor/remixicon/fonts/remixicon.css'%}">

    <body class=" ">        
        <div class="wrapper">
        <section class="login-content">
            <div class="container">
                <div class="row align-items-center justify-content-center height-self-center">
                    <div class="col-lg-5">
                        {% include 'alert/alert.html'%}
                        <div class="card auth-card">
                            <div class="card-body p-0">
                                <div class="d-flex align-items-center auth-content">
                                <div class="col-lg-12 align-self-center">
                                    <div class="p-3">
                                        <h2 class="mb-2">Sign In</h2>
                                        <p>Login to stay connected.</p>
                                        <form method="post" action="{% url 'App_Auth:login'%}">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="floating-label form-group">
                                                        <input class="floating-input form-control" required name="username" id="username" type="text" placeholder=" ">
                                                        <label>Username</label>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="floating-label form-group">
                                                        <input class="floating-input form-control" required name="password" id="password" type="password" placeholder=" ">
                                                        <label>Password</label>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6"></div>
                                                <div class="col-lg-6">
                                                    <a href="auth-recoverpw.html" class="text-primary float-right">Forgot Password?</a>
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Sign In</button>
                                        </form>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        </div>

       
        <script src="{% static 'assets/js/backend-bundle.min.js'%}"></script>
        <script src="{% static 'assets/js/table-treeview.js'%}"></script>
        <script src="{% static 'assets/js/customizer.js'%}"></script>
        <script async src="{% static 'assets/js/chart-custom.js'%}"></script>
        <script src="{% static 'assets/js/app.js'%}"></script>
    </body>
</html>

templates/inventory/users/addusers.html
{% extends 'inventory/base/base.html'%}
{% load static %}
{% block main %}

<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-6 mx-auto">
            {% include 'alert/alert.html'%}
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Add Users</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form action="" id="adduserform" method="post">{% csrf_token %}
                        <div class="row"> 
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    <label for="firstname">First Name *</label>
                                    <input type="text" class="form-control" name="first_name" id="firstname" placeholder="Enter Name">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>    
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="lastname">Last Name *</label>
                                    <input type="text" class="form-control" name="last_name" id="lastname" placeholder="Enter Name">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div> 
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="email">Email *</label>
                                    <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    <label for="username">UserName *</label>
                                    <input type="text" id="username" name="username" class="form-control" placeholder="Enter User Name">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    <label for="password1">Password</label>
                                    <input type="password" id="password1" name="password" class="form-control" placeholder="Enter Password">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>  
                            <div class="col-md-6">                      
                                <div class="form-group">
                                    <label for="password2">Confirm Password</label>
                                    <input type="password" id="password2" name="confirm_password" class="form-control" placeholder="Enter Confirm Password">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div> 
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="status">Status *</label>
                                    <select name="type" id="status" name="status" class="form-control" data-style="py-0">
                                        <option value="-1">Select</option>
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="usertype">User Type*</label>
                                    <select name="type" id="usertype" name="usertype" class="form-control" data-style="py-0">
                                        <option value="-1">Select</option>
                                        <option value="1">Admin</option>
                                        <option value="2" >Salesperson</option>
                                    </select>
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>                             
                        </div>                            
                        <button type="submit" class="btn btn-primary mr-2">Add User</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock %}

templates/inventory/users/edit.html
{% extends 'inventory/base/base.html'%}
{% load static %}
{% block main %}

<div class="container-fluid add-form-list">
    <div class="row">
        <div class="col-sm-6 mx-auto">
            {% include 'alert/alert.html'%}
            {% if user %}
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Edit Users</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{% url 'App_inventory:edituser' user.id %}" id="edituserform" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="firstname">First Name *</label>
                                    <input type="text" class="form-control" value="{{user.first_name}}"
                                        name="first_name" id="firstname" placeholder="Enter Name">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="lastname">Last Name *</label>
                                    <input type="text" class="form-control" value="{{user.last_name}}" name="last_name"
                                        id="lastname" placeholder="Enter Name">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="email">Email *</label>
                                    <input type="text" id="email" name="email" class="form-control"
                                        value="{{user.email}}" placeholder="Enter Email">
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="status">Status *</label>
                                    <select name="type" id="status" name="status" class="form-control"
                                        data-style="py-0">

                                        <option value="1" {% if user.is_active %} selected {% endif %}>Active</option>
                                        <option value="0" {% if not user.is_active %} selected {% endif %}>Inactive
                                        </option>
                                    </select>
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="usertype">User Type*</label>
                                    <select name="type" id="usertype" name="usertype" class="form-control"
                                        data-style="py-0">
                                        <option value="-1">Select</option>
                                        <option {% if user.is_superuser %} selected {% endif %} value="1">Admin</option>
                                        <option {% if not user.is_superuser %} selected {% endif %} value="2">
                                            Salesperson</option>
                                    </select>
                                    <div class="invalid-feedback"></div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Update User</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </form>
                </div>
            </div>
            {% else %}
            <div>
                <h4 class="text-center">No Data Found</h4>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- Page end  -->
</div>

{% endblock %}

templates/inventory/users/users.html
{% extends 'inventory/base/base.html'%}
{% load static %}
{% load custom_filters %}
{% block main %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex flex-wrap align-items-center justify-content-between mb-4">
                <div>
                    <h4 class="mb-3">User List</h4>
                </div>
                <a href="{% url 'App_inventory:adduser' %}" class="btn btn-primary add-list"><i
                        class="las la-plus mr-3"></i>Add User</a>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive rounded mb-3">
                <table class="data-table table mb-0 tbl-server-info">
                    <thead class="bg-white text-uppercase">
                        <tr class="ligth ligth-data">
                            <th>SL</th>
                            <th>FirstName</th>
                            <th>LastName</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>UserType</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody class="ligth-body">
                        {% for user in user_list %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{user.first_name}}</td>
                            <td>{{user.last_name}}</td>
                            <td>{{user.email}}</td>
                            <td>{{ user|active_status }}</td>
                            <td>{{ user|user_type }}</td>
                            <td>
                                <div class="d-flex align-items-center list-action">
                                    <a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title=""
                                        data-original-title="Edit" href="{% url 'App_inventory:edituser' user.id %}"><i
                                            class="ri-pencil-line mr-0"></i></a>
                                    <a href="javascripts:void(0);" userid="{{user.id}}" type="button"
                                        class="badge bg-warning mr-2 userdelete" data-toggle="modal"
                                        data-target="#deleteUserData"><i class="ri-delete-bin-line mr-0"></i></a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% include 'alert/pop.html'%}
<div class="modal fade" id="deleteUserData" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="exampleModalCenterTitle">Delete user from userlist.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                Are you really want to delete this user.?
            </div>
            <form method="post" action="{% url 'App_inventory:deleteuser'%}" class="modal-footer">
                {% csrf_token %}
                <input type="hidden" id="userdeletemodal" name="userdeletemodal" value="" />
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Delete</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}